# We want to only fetch the current version, without history.
# But we will fetch few more commits in case of rapid changes
# (new commit pushed in the middle of previous CI run).
git:
  depth: 5

os: linux
dist: bionic
language: node_js
node_js: node
services:
  - docker

# Based on https://github.com/nokia-wroclaw/innovativeproject-sudoku/blob/3402e16849db852167e6eadce6c952e889e2c1d2/.travis.yml
# Note that script continues even if one command fails.
jobs:
  include:
  - stage: test and lint backend
    before_install:
    - cd backend
    script:
    - npx eslint . --max-warnings=0
    - npm run test

  - stage: lint frontend
    before_install:
    - cd frontend
    script:
    - npx eslint src --max-warnings=0

  - stage: deploy
    if: branch = master
    before_install: skip
    install: skip
    script: skip
    deploy:
      provider: script
      on:
        # Don't run on forks.
        repo: nokia-wroclaw/innovativeproject-check-room
        branch: master
      script: bash docker/deploy-to-heroku.sh
