# Only fetch the current version, without history.
git:
  depth: 1

os: linux
dist: bionic
language: node_js
node_js: node
services:
  - docker

# Based on https://github.com/nokia-wroclaw/innovativeproject-sudoku/blob/3402e16849db852167e6eadce6c952e889e2c1d2/.travis.yml
# Note that script continues even if one command fails.
jobs:
  include:
  - stage: test and lint backend
    before_install:
    - cd backend
    script:
    - eslint . --max-warnings=0
    - npm run test

  - stage: test and lint frontend
    before_install:
    - cd frontend
    script:
    - eslint . --max-warnings=0
    - npm run test -- --watchAll=false

deploy:
  provider: script
  on:
    # Don't run on forks.
    repo: nokia-wroclaw/innovativeproject-check-room
    branch: master
  script:
    wget -qO- https://toolbelt.heroku.com/install.sh | sh
    echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
    heroku container:push web --app $HEROKU_APP_NAME
    heroku container:release web --app $HEROKU_APP_NAME
